#ifndef DRIVETRAIN_H
#define DRIVETRAIN_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "CANTalon.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class Drivetrain: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<CANTalon> frontLeftMotor;
	std::shared_ptr<CANTalon> rearLeftMotor;
	std::shared_ptr<CANTalon> frontRightMotor;
	std::shared_ptr<CANTalon> rearRightMotor;
	std::shared_ptr<RobotDrive> chassis;


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	bool blockJoysticks;
public:
	Drivetrain();
	void InitDefaultCommand();
	void DriveRobot(double move, double turn);
	void AutonTankDrive(double left, double right);
	void SetAutonomous(bool isAutonomous);
	bool GetAutonomous();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
