#include "Commands/PauseCommand.h"
#include "_CMG_ShootBall.h"
#include "Commands/ShooterActuate.h"
#include "Commands/ShooterSpeed.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

_CMG_ShootBall::_CMG_ShootBall() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
     // Add Commands here:
    // e.g. AddSequential(new Command1());
    //      AddSequential(new Command2());
    // these will run in order.

    // To run multiple commands at the same time,
    // use AddParallel()
    // e.g. AddParallel(new Command1());
    //      AddSequential(new Command2());
    // Command1 and Command2 will run in parallel.

    // A command group will require all of the subsystems that each member
    // would require.
    // e.g. if Command1 requires chassis, and Command2 requires arm,
    // a CommandGroup containing them would require both the chassis and the
    // arm.
		AddSequential(new ShooterActuate(false));
        AddSequential(new PauseCommand(0.5));
        SmartDashboard::PutBoolean("Shooter Ready", false);
        AddSequential(new ShooterSpeed(0.0, false));

 }
