#include "IntakeSpeed.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

IntakeSpeed::IntakeSpeed(double speed): Command() {
    m_speed = speed;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::intake.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void IntakeSpeed::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void IntakeSpeed::Execute() {
	Robot::intake->SetIntakeSpeed(m_speed);
}

// Make this return true when this Command no longer needs to run execute()
bool IntakeSpeed::IsFinished() {
    return Robot::shooter->GetPhotoeye();
}

// Called once after isFinished returns true
void IntakeSpeed::End() {
	Robot::intake->SetIntakeSpeed(0.0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void IntakeSpeed::Interrupted() {
	End();
}
