#include "ShooterActuate.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

ShooterActuate::ShooterActuate(bool upDirection): Command() {
    m_upDirection = upDirection;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	//Requires(Robot::shooter.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void ShooterActuate::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void ShooterActuate::Execute() {
	if(m_upDirection) {
		Robot::shooter->SetShooterDirection(frc::DoubleSolenoid::kReverse);
	}else{
		Robot::shooter->SetShooterDirection(frc::DoubleSolenoid::kForward);
	}
}

// Make this return true when this Command no longer needs to run execute()
bool ShooterActuate::IsFinished() {
    return true;
}

// Called once after isFinished returns true
void ShooterActuate::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ShooterActuate::Interrupted() {

}
